/* Resource file definitions for the common Okino COM client source files */

/* A message ID used to have the dialog box refresh its contents */
#define	WM_UPDATE_DIALOG_PARAMETERS	(WM_USER+20)
/* A message ID used to have the dialog box refresh the enable states of its controls */
#define	WM_UPDATE_DIALOG_ENABLES	(WM_USER+21)

// Some common defines
#define IDD_BUTTON_HELP		995
#define IDD_BUTTON_RESET	996
#define IDD_BUTTON_ABOUT	997
#define IDR_TYPELIBRARY		998

// Options for a batch conversion operation
#define IDD_BATCHCONVERT_SHOWEXPORTEROPTIONS		1000
#define IDD_BATCHCONVERT_EXPORT_DIRECTORY_EDIT		1002
#define IDD_BATCHCONVERT_EXPORT_DIRECTORY_BROWSE	1003
#define IDD_BATCHCONVERT_LOCK_IMPORT_EXPORT_DIRS	1004
#define IDD_BATCHCONVERT_RESIZEMODELTOEXTENTS		1007
#define IDD_BATCHCONVERT_ADDLIGHTSTOSCENEIFNONE		1008
#define IDD_BATCHCONVERT_DOPOLYPROCESSING		1009
#define IDD_BATCHCONVERT_SHOW_POLYPROCESSING_OPTIONS	1010
#define IDD_BATCHCONVERT_DOPOLYREDUCTION		1011
#define IDD_BATCHCONVERT_SHOW_POLYREDUCTION_OPTIONS	1012
#define IDD_BATCHCONVERT_CREATEBACKUPSDURINGEXPORT	1013
#define IDD_BATCHCONVERT_INPUT_FILENAME			1014
#define IDD_BATCHCONVERT_INPUT_FILE_FORMAT		1015
#define IDD_BATCHCONVERT_SHOW_IMPORT_OPTIONS		1016
#define IDD_BATCHCONVERT_COMPRESS_CHILDREN_ENA		1017
#define IDD_BATCHCONVERT_SHOW_COMPRESS_CHILDREN_OPTIONS	1018
#define IDD_BATCHCONVERT_ENA_HIER_OPT1			1019
#define IDD_BATCHCONVERT_ENA_HIER_OPT2			1020
#define IDD_BATCHCONVERT_APPLY_GLOBAL_XFORM_ENA		1021
#define IDD_BATCHCONVERT_SHOW_GLOBAL_XFORM_OPTIONS	1022
#define IDD_BATCHCONVERT_PERFORM_CONVERSION_VISIBLE_IN_VIEWPORTS 1023
#define IDD_BATCHCONVERT_RENDER_SNAPSHOT_ENABLE		1024
#define IDD_BATCHCONVERT_RENDER_RES_X			1025
#define IDD_BATCHCONVERT_RENDER_RES_Y			1026
#define IDD_BATCHCONVERT_RENDER_SCANLINE_AA_COMBO	1027
#define IDD_BATCHCONVERT_RENDERLEVEL_SCANLINE_RB	1028
#define IDD_BATCHCONVERT_RENDERLEVEL_RAYTRACE_RB	1029
#define IDD_BATCHCONVERT_RENDER_FILE_FORMAT_COMBO	1030
#define IDD_BATCHCONVERT_EXPORT_TYPE_COMBO		1031

/* Geometry import status dialog box */
#define	IDD_GEOMIMPORT_CANCEL			1000
#define	IDD_GEOMIMPORT_LINE_NUM			1001
#define	IDD_GEOMIMPORT_TOTAL_OBJECTS		1002
#define	IDD_GEOMIMPORT_LINE_NUM_TEXT		1003
#define	IDD_GEOMIMPORT_TOTAL_OBJECTS_TEXT	1004
#define	IDD_GEOMIMPORT_TEXT			1005
#define	IDD_GEOMIMPORT_TOTAL_POLYS		1006
#define	IDD_GEOMIMPORT_TOTAL_POLYS_TEXT		1007
#define	IDD_METER_CONTROL			1008

/* Geometry export status dialog box */
#define IDD_GEOMEXPORT_HANDLETYPE		1000
#define IDD_GEOMEXPORT_HANDLENAME		1001
#define IDD_GEOMEXPORT_PROCESSING		1002
#define IDD_METER_CANCEL			1004

/* Server not responding dialog box */
#define IDC_SERVERFAULT_RETRY_OPERATION		1000
#define IDC_SERVERFAULT_RESTART_SERVER		1001
#define IDC_SERVERFAULT_CANCEL_OPERATION	1002
#define IDC_SERVERFAULT_HELP			1003
#define IDC_SERVERFAULT_ERROR_MSG		1004
